const { MongoMemoryServer } = require('mongodb-memory-server');
const mongoose = require('mongoose');

let mongoServer;

// Test environment setup
beforeAll(async () => {
  // Set test environment variables
  process.env.NODE_ENV = 'test';
  process.env.MONGODB_URI = 'mongodb://localhost:27017/test_agreeproof';
  process.env.FRONTEND_URL = 'http://localhost:3000';
  
  // Start in-memory MongoDB server
  mongoServer = await MongoMemoryServer.create();
  const mongoUri = mongoServer.getUri();
  
  // Connect to the in-memory database
  await mongoose.connect(mongoUri);
  
  console.log('Test database connected');
});

// Cleanup after each test
afterEach(async () => {
  // Clear all collections after each test
  const collections = mongoose.connection.collections;
  
  for (const key in collections) {
    const collection = collections[key];
    await collection.deleteMany({});
  }
});

// Test environment teardown
afterAll(async () => {
  // Disconnect from database
  await mongoose.disconnect();
  
  // Stop the in-memory MongoDB server
  if (mongoServer) {
    await mongoServer.stop();
  }
  
  console.log('Test database disconnected');
});

// Global test utilities
global.testUtils = {
  // Create a test agreement data object
  createTestAgreementData: (overrides = {}) => ({
    title: 'Test Agreement',
    content: 'This is a test agreement content for testing purposes.',
    partyA: {
      name: 'John Doe',
      email: 'john.doe@example.com'
    },
    partyB: {
      name: 'Jane Smith',
      email: 'jane.smith@example.com'
    },
    ...overrides
  }),
  
  // Create a test agreement in database
  createTestAgreement: async (AgreementModel, data = {}) => {
    const { generateAgreementId, generateProofHash } = require('../src/utils/generateId');
    
    const testData = global.testUtils.createTestAgreementData(data);
    
    // Add required fields that are normally generated by the controller
    testData.agreementId = testData.agreementId || generateAgreementId();
    testData.proofHash = testData.proofHash || generateProofHash(testData);
    
    const agreement = new AgreementModel(testData);
    return await agreement.save();
  },
  
  // Wait for a specified time (for async operations)
  wait: (ms) => new Promise(resolve => setTimeout(resolve, ms)),
  
  // Generate random test data
  randomEmail: () => `test${Math.random().toString(36).substring(7)}@example.com`,
  randomString: (length = 10) => Math.random().toString(36).substring(2, length + 2)
};

// Suppress console logs during tests unless explicitly needed
if (process.env.NODE_ENV === 'test') {
  const originalConsoleLog = console.log;
  const originalConsoleError = console.error;
  const originalConsoleWarn = console.warn;
  
  console.log = (...args) => {
    if (process.env.SHOW_TEST_LOGS === 'true') {
      originalConsoleLog(...args);
    }
  };
  
  console.error = (...args) => {
    if (process.env.SHOW_TEST_LOGS === 'true') {
      originalConsoleError(...args);
    }
  };
  
  console.warn = (...args) => {
    if (process.env.SHOW_TEST_LOGS === 'true') {
      originalConsoleWarn(...args);
    }
  };
}